### ISSUE TITLE
Lab 03 - Potentially redundant/duplicate user creation steps.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#1]
# Module: 00
#### Step: 04/05

Description of issue

In 'Lab 01: Manage user roles', the user Chris Green is created but never deleted, at least in this lab.  In 'Lab 03: Assigning licenses using group membership', the same user Chris Green is created again.  

While I can see this being needed if every lab is taken independently, given the relatively short length of these labs it is likely students will be taking multiple #s of them consecutively in one session and thus already will have that user created when they get to this lab.  It might be good to either have a short note indicating 'If you still have the user Chris Green, please skip these steps'.  

Alternatively, it might flow better if the username created in that task was simply changed into a differently named user then 
 the already-created Chris.

**Comment by R-C-Stewart** [comment]
Agreed - I am in the process of revamping the labs to get rid of these types of redundant steps.  We appreciate your finding and submitting this issue.  And look forward to hearing from you in the future.
