### ISSUE TITLE
Remove Ex 2 from Lab 21 - in the wrong Learning path and repeated in Lab 24

### ISSUE THREAD

**Issue by joannex** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#106]
# Module: 04
#### Step:
Description of issue

Remove Ex 2 from Lab 21 - in the wrong Learning path and repeated in Lab 24

**Comment by R-C-Stewart** [comment]
I have no idea how that duplication of lab existed this long.  Thanks for the pointer.  It should be fixed now.
