### ISSUE TITLE
Lab 25 - extra info

### ISSUE THREAD

**Issue by joannex** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#108]
# Module: 05
#### Step: 09 - additional info needed before moving on to settings such as the below as you need to select a reccurence in an AR.
"Choose a reviewer, select a review recurrence, then click settings. "
#### Step: 11 Creat should read create

**Comment by R-C-Stewart** [comment]
Fixed... I think this is a UI must have changed.  I thought you set recurrence in a different spot.
