### ISSUE TITLE
Unable to perform Lab 16 Exercise 1 Task 5

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#115]
#### Step: 02

Description of issue
Unable to execute the command

![image](https://user-images.githubusercontent.com/98971092/216036752-b1fad988-40d4-4402-8abd-1d6151743917.png)

Repro steps:

1. Perform all pre-requisite steps and execute the PowerShell command

**Comment by R-C-Stewart** [comment]
Thank you for the submission... I was able to reproduce and find a fix for this issue.  I am updating the lab today, and you should not run into the problem in the future.  The setting to create a Service Principal has moved in the UI; and therefore was not in the steps correctly.
