### ISSUE TITLE
Lab_01_ManageUserRoles.md - using New-MgUser

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#126]
# Lab 01: Manage user roles
### Task 2 - Bulk addition of users using PowerShell

With the retirement of the **MicrosoftOnline** and **AzureAD** modules, this lab needs to be updated to use the **Microsoft.Graph** module. Something like the following.

_____

#### Check PowerShell Version 

1. Open **PowerShell 7** as an administrator. This can be done by clicking the Start Menu, typing **pwsh**, right-clicking on **PowerShell 7 (x64)** and choosing **Run As Administrator**. Select **Yes** at the UAC prompt.

1. If the PowerShell version is earlier than 7.2 then close the PowerShell 7 window and perform the following step. Otherwise skip to the next section.

1. Open Microsoft Edge. Navigate to **https://aka.ms/PowerShell-Release?tag=v7.3.1**. Scroll down to the **assets** section and select **powershell-7.3.1-win-x64.msi**. When the download has completed, select **Open file**. Install using all the defaults.

#### Install the module 

1. In the administrative **PowerShell 7** window, enter the following.

    ````powershell
    Install-Module Microsoft.Graph -Scope CurrentUser
    ````

1. If asked to confirm downloading from an untrusted repository then enter **y**.

1. Close the administrative PowerShell 7 window.

#### Create a user

1. Open **PowerShell 7**.

1. Sign in to Azure by entering the folowing.

    ````powershell
    Connect-MgGraph -Scopes "User.ReadWrite.All"
    ````

1. When Microsoft Edge opens, sign in as **MOD Administrator**.

1. At the **Permissions requested** page, enable **Consent on behalf of your organization** and then select **Accept**.

1. Close the Microsoft Edge browser tab and return to PowerShell.

1. Create a password profile object. Replace Pa55w.rdPa55w.rd with a complex password of your choice.

    ````powershell
    $PWProfile = @{
        Password = "Pa55w.rdPa55w.rd";
        ForceChangePasswordNextSignIn = $false
    }
    ````

1. Create a user. Replace **labtenantname.com** with the **.onmicrosoft.com** name assigned to your tenant.

    ````powershell
    New-MgUser `
        -DisplayName "Rene Magi" `
        -GivenName "Rene" -Surname "Magi" `
        -MailNickname "renemagi" `
        -UsageLocation "NZ" `
        -UserPrincipalName "rene@labtenantname.com" `
        -PasswordProfile $PWProfile -AccountEnabled `
        -Department "Research" -JobTitle "Subject Matter Expert"
    ````

**Comment by R-C-Stewart** [comment]
This is now fixed and should go live on November 1st.
