### ISSUE TITLE
Lab22-Ex01-Task01-Step7: If disable is selected, it hides the option to review step 8

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#129]
# Lab/Demo: 22
#### Step: 07

Description of issue: If disable is selected, it hides the option to review step 8

Repro steps:
1. Do step 7, it hides "Enabled for external users" option, so it cannot be seen in step 8

Recommendation:
1. Put step 8 BEFORE step 7, even as a Note if needed.

**Comment by R-C-Stewart** [comment]
Thank you...  I have fixed this issue.
