### ISSUE TITLE
When will labs be updated to recent Major update to course?

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#132]
Major update to SC-300 course, change log states 
• Updated labs to align to use the Microsoft Entra admin center as the primary configuration
and management tool.

PPT's updated, content on MSLearn updated, no updates to labs.

Could you please provide a date as to when the labs hosted here will be updated?

**Comment by R-C-Stewart** [comment]
Updates are happening this week.  Should be live for deliveries starting on Nov 6.  I tried to have them refreshed for this week, but UI changes kept breaking my fixes, so I am delayed by a week.

**Comment by R-C-Stewart** [comment]
Done -- except for Lab 7, which is broken due to licensing and we are trying to find a fix.
