### ISSUE TITLE
Cannot create new tenant for Lab 07 with Azure Pass subscription

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#134]
# Module: 02
##### Step: 06

Description of issue
Error: "Only paid customers can create a Microsoft Entra Workforce tenant."
and "Microsoft Entra ID" option is not available.

This is my tenant (MCT) in class using an Azure Pass.
![Screenshot 2023-10-30 131242](https://github.com/MicrosoftLearning/SC-300-Identity-and-Access-Administrator/assets/20519564/a706d1f4-dcf4-419f-b245-d8adfa7ec583)

**Comment by ITBlandMCT** [comment]
Hmmm, I seem to have some other issue...

**Comment by ITBlandMCT** [comment]
Something changed with Azure Pass???

**Comment by R-C-Stewart** [comment]
I am testing this today, and will let you know what I can figure out.  Does not mean much, but this did work two weeks ago.

**Comment by grabery** [comment]
Same issue here! Being an MCT providing a course to 12 students, this is fun. Nobody able to create a tenant in their lab as provided and described by Microsoft. in the lab description...

@R-C-Stewart the same procedure worked for all my courses I provided the last years, first time I run into this problem today. For me it's clear, that this means something... A Microsoft change :-)

**Comment by R-C-Stewart** [comment]
Yes - There was a licensing change on October 30 that broke this lab, AZ-104, and AZ-500 similar labs.  We did not know it was coming, and are working to get a fix in place.  You do have our deepest apologies.

**Comment by Yiizo** [comment]
Has this been fixed yet?

Thanks in advance

**Comment by grabery** [comment]
@Yiizo no, it's not fixed yet. Still the same issue last week, as I was teaching AZ-500 course. And luckily enough, there are lab dependencies, so it's not one but 2 labs that are not functional in AZ-500 for now.

**Comment by R-C-Stewart** [comment]
Correct, these labs are not working right now.  I am working with out BG product developers and the lab platform to find an answer for this.  We will keep you posted.  Licensing / Fraud change caused this.  I have marked lab 7 as optional in SC-300 and put a note about the problem.  You should be able to use the lab on a personal subscription, if you really wanted to test.

Robert

________________________________
