### ISSUE TITLE
LabVM OS versions are mixed up

### ISSUE THREAD

**Issue by petender** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#138]
# Module: 02
#### Step: 07

Instructions point to the Server Dashboard + later on to RDP into Server 2022, but earlier instructions tell us to deploy a Windows 11 Azure VM, not a server OS version

Instructions should be updated to either deploy a Server 2022 OS, or updated to not point to the Server dashboard in the task details

**Comment by R-C-Stewart** [comment]
Good catch.  I have fixed this in the lab.  As I am sure you remember, I used to do this lab with a Windows Server VM.  But it works the same with Windows Client, and it deploys much quicker.
