### ISSUE TITLE
Defender for Cloud Apps access policy cannot be created

### ISSUE THREAD

**Issue by abelchior77** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#139]
# Module: 03
#### Step: 06

Description of issue - Cannot create policy due conditional client app control not exist

Conditional access created according previous step but not populated into Defender for Cloud App

Alex

**Comment by R-C-Stewart** [comment]
I was not able to duplicate your issue.  However, I found several changes that can make the lab easier to follow, and made those updates.  I am hoping that will clear up the problem.  NOTE - you should complete Exercise1 or this lab before you work on this second Exercise.
