### ISSUE TITLE
Optional lab Exercixe 2 Lab 10

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#141]
#### Step: 3

18.04 LTS no longer exists, Please change the dialog as some setting are different or have changed.

**Comment by R-C-Stewart** [comment]
Thanks for the submission... I will get this updated for the end of week release.

**Comment by R-C-Stewart** [comment]
I still see the 18.04 LTS in my list.  However, I have modified the lab to be a little more generic in the selection.  You can actually most of the options listed, and get the same capabilities.
