### ISSUE TITLE
Using the previous name, Azure AD, in the lab guide

### ISSUE THREAD

**Issue by Philipnyeung** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#142]
Using the previous name, Azure AD, in the lab
 Lab 01, 02, 10, 27

**Comment by R-C-Stewart** [comment]
Fixed ---> THANK YOU so much for calling this out. Lab 1 and 2 are on me.  I had updated these and missed some references.  Sorry, you had to find them.  Labs 10 and 27, I waited so long for those to change.  Glad to see the UI has been updated.
