### ISSUE TITLE
Instructed queries are missing in Lab 27 - Exercise 1 - Task 3

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#144]
Lab 27 - Exercise 1 - Task 3 - Step 7 - Can make it into Threat Management and select Hunting, but after that, no queries or previews are available, and no additional windows open to locate the Anomolous sign-in location by user account and authentication application that is indicated in step 7 [p1].

Looks like a UI/UX update in Azure may have relocated them or removed them entirely, but the query isn't viewable as written in the instructions [p2].

[p1] 

![image-1](https://github.com/MicrosoftLearning/SC-300-Identity-and-Access-Administrator/assets/94069201/23033ed2-8417-4562-b491-a0c555e8b77a)

[p2]

![image](https://github.com/MicrosoftLearning/SC-300-Identity-and-Access-Administrator/assets/94069201/98b5064d-ea8e-42b4-9d0f-9602b1b8fb7e)

**Comment by R-C-Stewart** [comment]
Thank you for letting me know.  I will work on this Friday, so I don't interupt any on-going labs.

**Comment by SkillableBB** [comment]
Hi @R-C-Stewart, was this resolved?

**Comment by R-C-Stewart** [comment]
Hmmm... I swear I posted an update to this.  The last up to Microsoft Sentinel broke this Hunting steps, from what I can tell there are no longer any built-in queries for Microsoft Entra ID data connector.  I had dropped the last 3 steps, to keep the lab but remove the failure.  I will resubmit the change.
