### ISSUE TITLE
Lab 10 RDP issue

### ISSUE THREAD

**Issue by JxNichols2023** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#145]
# Module: 3
#### Step: 7

Description of issue Since RDP does not support MFA you cannot logon as the AzureAD user Joni.  
Repro steps:

1.Followed the lab exactly as written  but JoniS cannot logon.  I tested it on my personal subscription that does not require MFA and it works.  
1.
1.

**Comment by R-C-Stewart** [comment]
We are making some changes to the MFA implementation that should fix this issue.  I am not changing the lab now, but it should be fixed any time now.
