### ISSUE TITLE
SC-300 Lab Content Issues (Fast Lane Practice Lab)

### ISSUE THREAD

**Issue by GithubGIFG** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#147]
Hi there. Both Fast Lane and Skillable Support told me to submit the following on this repository. I found more errors and issues with SC-300 lab on Fast Lane: 

I went through Module 4 again, and here are the following errors:

Lab 23: Add terms of use and acceptance reporting
17. Under Assignments, select Users or workload identities. <-- Workload does not appear (just “Users”)
20. Select Cloud apps or actions. <-- now "Target Resources"
Task 6 - Edit terms of use details <-- does not appear to work. I have logged out and logged back in as global admin, but the newly created Terms of Use cannot be edited. This also applies to Task 7.

Lab 24: Manage the lifecycle of external users in Microsoft Entra Identity Governance settings
Exercise 1 = Settings are grayed out, like the signin account has no permissions. Checked and determined that [admin@LODSM650212.onmicrosoft.com](mailto:admin@LODSM650212.onmicrosoft.com) is a Global Admin. Not sure why.

Lab 26: Configure Privileged Identity Management for Microsoft Entra roles
Task 3 - Activate your Microsoft Entra roles (as Miriam)
6. In the Activate – Compliance Administrator pane, select Additional verification required and then follow the instructions to provide additional security verification. You are required to authenticate only once per session. <-- Did not see any "Additional verification required" when I selected Active

Lab 27 - Microsoft Sentinel Kusto Queries for Microsoft Entra data sources
Task 3 - Run Kusto query on User activity
7. Scroll down to find the query "Anomalous sign-in location by user account and authenticating application". This query over Microsoft Entra sign-in considers all user sign-ins for each Microsoft Entra application and picks out the most anomalous change in location profile for a user within an individual application. The intent is to hunt for user account compromise, possibly via a specific application vector.
<-- Could not find the query. Error message: "Hunting Query with "content source = gallery content" has been removed. All the removed c content and more is available in content hub. Click here to reinstate in use "content source = gallery content" templates". Searched for "Anomalous" and "UEBA Essentials" showed up. Installed it. However, the specific query could not be found, so instead used "Anomalous Sign-In Activity" query which of course errored: "'where' operator: Failed to resolve table or column expression named 'BehaviorialAnalytics'".

Lab 28 - Monitor and managed security posture with Identity Secure Score
Task 2 - Execute an improvement action
1. To improve one area of the identity security posture, select Protect all users with a sign-in risk policy. <-- Does not exist. There are 10 improvements, but the one in question does not exist.

I ended the course since I was running out of time (even after one 60-minute extension) since I was documenting the above errors."

Note also that I just completed my second attempt with SC-300 exam (which I again failed, this time by 32 points). The following items were covered in the exam but not in the SC-300 practice lab:
- Entra Permissions Management: No lab available but the exam had about 5 or 7 questions on Permissions Management.
- Entra Privileged Identity Management: Really needs to be revamped since the practice in the lab did not reflect what was being asked in the exam.
- Implement access management for Azure resources by using Azure roles: Need more lab exercises. Lots of questions in the exam in different flavors.

Any questions or need more details, let me know.

**Comment by R-C-Stewart** [comment]
Thank your for your feedback in this ISSUE, it is greatly appreciated.  And apologies for taking so long to follow-up.  I had actually addressed quite a few of these items over the last few weeks, but never updated the bug.  Overall, I have fixed the noted bugs at the beginning of this Issue. The Sentinel lab, I have reduced down, because Sentinel is not really even part of the OD for this course.  The requests for more content on Permissions Management and PIM, I will see what I can do.  The licensing for Permissions Management is currently the blocker on that lab, it requires a credit card.  I want to include a lab.  PIM, I will look back at the OD and see where we can expand.
