### ISSUE TITLE
Lab 10 Task 6(Optional TAsk)

### ISSUE THREAD

**Issue by shahanakattil** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#151]
# Module: 10
#### Step: 04

Description of issue
In Task 6 when we are logging into the VM using the Entra ID credentials. Not able to see the Entra ID user in the Administrators group as mentioned in the guide.
Repro steps:

1.
1.
1.

**Comment by R-C-Stewart** [comment]
I was not able to directly reproduce this issue.  However, in testing I made a couple of minor updates to the steps to hopefully make the process clearer.  You should not be able to log in with Entra ID, if the user is not in the group.  The other possibility is if you chose "Virtual Machine User Login."  Then the account would be in the USERS group instead.
