### ISSUE TITLE
Bad directions for VM creation

### ISSUE THREAD

**Issue by WFStorms** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#153]
# Module: 02
#### Step: 4-6

Description of issue:

The default values of these steps are for a trusted launch VM.  The Azure Pass does not allow for this, resulting in errors and frustration for learners.  Please specify exact values for VM configuration.

Repro steps:

1.
1.
1.

**Comment by R-C-Stewart** [comment]
Thanks for letting me know.  I had not experienced this in my testing; but I will go through the steps and modify to account for this challenge.

**Comment by R-C-Stewart** [comment]
This should be updated now.  I went with fully qualified the VM-settings and tested it out.  Agreed that it did not work in East-US, where it has always worked in the past.  I cannot find a feature missing from the datacenter that would cause it to fail, but it does.  It did work in other datacenters I tried (like West-US).  I am going to close this one, based on my changes.
