### ISSUE TITLE
Lab 16 unable to connect to the remote server error msg

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#154]
# Module: 00
#### Step: 2

Description of issue

unable to connect to the remote server error msg

I am aware of the closed ticket

![WhatsApp Image 2024-09-18 at 17 04 39_63d740f6](https://github.com/user-attachments/assets/58438429-a03f-498b-88e8-6cca69217d2a)

I assue the 169.254.169.254 is to retrieve metatdata using an API?

Repro steps:

1.
1.
1.

**Comment by R-C-Stewart** [comment]
Thank you... I know this one worked as of 2 weeks ago.  I was away last week for a work event, so have not tested it recently.  I will check it today, and update by the end of the week as needed.
