### ISSUE TITLE
Lab 03: Assigning licenses using group membership GUI drift

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#157]
# Module: 00
#### Step: 03

Description of issue
GUI drift, license assignment must use admin.microsoft.com, unable to use entra.microsft.com anymore
Repro steps:

1.
1.
1.

**Comment by R-C-Stewart** [comment]
Thank you... I will get this updated by the end of the week.

**Comment by dpapkin** [comment]
> Thank you... I will get this updated by the end of the week.

the entire module needs to be updated. many of the labs dont work anymore from lab 10 onwards

**Comment by R-C-Stewart** [comment]
Due to the forced MFA change that is coming, my lab update has been delayed.  I am testing and updating labs end-to-end.  I do appreciate your feedback and will get everything cleaned up for you and our students / trainers.

**Comment by nestorreveron** [comment]
> Debido al cambio forzado de MFA que se avecina, la actualización de mi laboratorio se ha retrasado. Estoy probando y actualizando los laboratorios de principio a fin. Agradezco sus comentarios y haré que todo quede en orden para usted y nuestros estudiantes/capacitadores.

Thanks

**Comment by R-C-Stewart** [comment]
This should be updated now.
