### ISSUE TITLE
Mod 1 (Labs 1-9, 12-15, 17-26, 28) Out-dated Images

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#161]
# Module: 01
Description of issue:
- outdated images

Repro steps:
- Please update the images at the following steps to match the current UI:

Lab 8 Exercise 1 task 2 Step 12
Lab 9 Exercise 1 Task 1 Step 4
Lab 12 Exercise 1 Task 1 Step 5
Lab 13 Exercise 1 task 2 Step 15
Lab 13 Exercise 3 Task 1 step 17
Lab 23 Exercise 1 Task 1 Step 15

**Comment by R-C-Stewart** [comment]
Fixed... Still need to replace the Lab 23 picture, but the rest should be up to date.
