### ISSUE TITLE
Lab 07 - Wrong username referenced

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#2]
# Module: 00
#### Step: 05

Description of issue

In 'Lab 07: Change user account license assignments', task 'Create a new user in Azure Active Directory', Step 5, the user is referred to as 'Chris Green', when it should be 'Dominique Koch'.

**Comment by R-C-Stewart** [comment]
Fixed -- thanks for finding and submitting this issue.
