### ISSUE TITLE
Lab 12/14 - potentially reorganization of modules for clarity?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#3]
# Module: 00
#### Step: 11

Description of issue

In Lab 12 - 'Enable Azure AD multi-factor authentication', in Task 'Setup conditional access rules for MFA' where one is setting up MFA it will fail w/error 'Security defaults must be disabled to enable Conditional Access policy' in Step 11 unless 'Enable Security defaults' is set to No for the subscription being used.

Since in most/many cases this value will be set to 'Yes' by default, and thus is a predictable error: it *might* be a good idea to have the steps in Lab 14 - 'Working with security defaults' occur before Lab 12.

Alternatively, a 'Note' could be included in Step 11 of Lab 12 indicating to the student that if they receive this error to jump to Lab 14 to fix for it.

**Comment by R-C-Stewart** [comment]
Thanks for the feedback, and I do agree with you.  I made a ton of updates the labs that went live today (9/10/2021) and I think I resolved the issue you mention.  Have a look and let me know if you feel like further changes are necessary.
