### ISSUE TITLE
Mod 1 - user can add an application when they shouldn't be able to

### ISSUE THREAD

**Issue by joannex** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#33]
# Module: 01
#### Step: 6

Description of issue
User CAN add an application here......the notes say they would not be able to....
Repro steps:

1.
1.
1.

**Comment by erickamor** [comment]
Turns out yes they do see "+ New Application", but when they select an item from the gallery the final 'Create' button is unavailable.

**Comment by R-C-Stewart** [comment]
Thanks for the feedback. we will tweak this to show the UI change.  I am sure that when I built the lab originally, the + New was greyed out; but Azure changes so often <smile>.
