### ISSUE TITLE
Azure pass 

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#40]
Lab 00: Lab Environment Setup
Description of issue
I'm using Learn On Demand LAB

Implement an identity management solution (Expected Duration 1 hours, 55 minutes)
SC-300T00-A Microsoft Identity and Access Administrator [Azure Pass Required], Module 01

I the first Step, students has to add a azure pass using the office 365 credentials that is generated 

In this course, students don't need a azure pass !!! JUste p2 license
So why asking this in the setup guide

Also in the next module
Implement an authentication and access management solution (Expected Duration 2 hours, 25 minutes)
SC-300T00-A Microsoft Identity and Access Administrator [Azure Pass Required], Module 02
A new admin office 365 is generated !!!!!!!!
So the azure pass is lost !!!! as the student has new office 365 credentials

SO the issue is from vm from learn on demand as new office 365 credentials are generated with each lab
The solution could be to generate only one VM for all the training 

How can we solve this issue as Monday I have 10 students !!!

Repro steps:

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue

**Comment by R-C-Stewart** [comment]
Fixed on 2/4/2022 release.  Azure Pass no longer used.
