### ISSUE TITLE
Mfa password typo error

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#41]
Lab 12 - Enable Azure AD multi-factor authentication
Exercise 1 - Review and enable Multifactor Authentication in Azure
Task 3 - Test Delia's login

Enter the password = pass@word123. ???
We have to ue the password tenant !!  it's a typo error
Can you check please

**Comment by MOC-Labs-Review** [comment]
This issue has been resolved by MOC Labs Review pull request #48

**Comment by R-C-Stewart** [comment]
We are removing all passwords and asking the students to control passwords.  So, this is fixed of 2/4/2022 release.
