### ISSUE TITLE
Lab_31_ConnectDataFromAADToAzureSentinel.md -- 'Azure Sentinel' now renamed to 'Microsoft Sentinel'

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#42]
# Module: 04
#### Step: 02

Description of issue

 'Azure Sentinel' now renamed to 'Microsoft Sentinel'.  There are several places in the text this should be updated, but in particular in Step 2 where student searches for it, it will now appear as "Microsoft Sentinel':

![image](https://user-images.githubusercontent.com/49700217/147416070-60123101-4a3d-4d9c-9289-feea8c8017c6.png)

**Comment by MOC-Labs-Review** [comment]
This issue has been solved by MOC Labs Review pull request #58

**Comment by R-C-Stewart** [comment]
Fixed ... thanks for the submission.  I tried to catch all these; but missed a few.
