### ISSUE TITLE
Misleading instruction about secret's value in Lab22

### ISSUE THREAD

**Issue by houbena** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#44]
#### Step: 6

Description of issue:

The instructions of step 6 says: "Record the secret's value for use in your client application code; It's **never displayed again after you leave this page**."

Actually, the secret's value is displayed after leaving the page and back. However, logging out and in again show an obfuscated value.

**Comment by R-C-Stewart** [comment]
We updated the language.  I think it cleans up the issue you are describing.  Thanks for the submission.
