### ISSUE TITLE
Lab 24: Hyperlink incorrect

### ISSUE THREAD

**Issue by BurgerhoutJ** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#5]
## Lab/Demo: 24

Description of issue
Hyperlink on rule 51 is incorrect. 
Sign in to [https:portal.azure.com] (https:portal.azure.com).

It should be:
Sign in to [https://portal.azure.com](https://portal.azure.com).

**Comment by R-C-Stewart** [comment]
Fixed - thank you for finding this and submitting!
