### ISSUE TITLE
Lab26 - Should not require Require users to consent on every device

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#59]
# Module: 4
#### Step: 00

With "Require users to consent on every device" on, the user will have to register the device with AAD, this requires extra steps not covered in this lab. We should not enable this option

**Comment by R-C-Stewart** [comment]
I have updated to OFF.  I did test the lab with using the ON state, and did not seem to find any problems.  But I can understand the potential challenge.  So for now, we will go with Off and see if there are any challenges.
