### ISSUE TITLE
Will these labs be updated for the new version of the course and as there is no longer an azure pass for this, will any lab requiring azure be removed?

### ISSUE THREAD

**Issue by joannex** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#85]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1.
1.
1.

**Comment by R-C-Stewart** [comment]
All labs were updated and released over the last month.  We are ironing out a few bugs still; but overall the labs are revamped for the updated version of the course and OD.
