### ISSUE TITLE
Lab 07 Deployment failed

### ISSUE THREAD

**Issue by jmenne** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#86]
#### Step 6

Deployment of the Template failed. Seems there is a problem with the Powershell DSC Extension! 

Resource ADDC failed. Status message is:
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'InstallDomainController'. Error message: \\\"DSC Configuration 'CreateADPDC' completed with error(s). Following are the first few: The password supplied to the Desired State Configuration resource MSFT_xADDomain is not valid. The password cannot be null or empty. The SendConfigurationApply function did not succeed.\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot \"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}

**Comment by R-C-Stewart** [comment]
There is currently an issue with Windows Datacenter Server (a failed patch) that is preventing this lab from completing.  We are testing each week to see if / when the lab works again; and will notify the lab takers at that point.  You have not done anything wrong.
