### ISSUE TITLE
Lab 12_Lockout threshold not working as expected

### ISSUE THREAD

**Issue by abhishekak1212** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#88]
# Module: 00
#### Step: 00

Description of issue
If someone can explain if there is any issue with Lab 12 - Custom Smart Lockout feature not locking out as per the threshold set.
Repro steps:

1.
1.
1.

**Comment by Dimmmer** [comment]
Unable to repro your issue - it does work as expected.
