### ISSUE TITLE
Lab 7 App service Domain Deployment fails

### ISSUE THREAD

**Issue by rtrader58** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#89]
# Module: 01
#### Step: 08 - 12

Description of issue
App Service Domain deployment fails with the following error.
Repro steps:

![App Service](https://user-images.githubusercontent.com/46455953/186004725-e46f8420-b384-423e-9a1a-97831f08f147.JPG)
![App Service 2](https://user-images.githubusercontent.com/46455953/186004853-19d45884-7d8d-4245-ba11-6403b2223b4c.JPG)

**Comment by chrzanowskiItta** [comment]
Hello I have the same issue

**Comment by chrzanowskiItta** [comment]
did you find a solution ?

**Comment by rtrader58** [comment]
If you are referring to Lab 07 Purchasing a Domain, no I did not.  But it does not affect the rest of the lab.  Students can complete the remaining steps.  I tell them to disregard the error and continue.


Rick Trader

Interface Technical Training

Systems Engineering Trainer | IT Manager



Phone (602) 266-8500 Ext. 8565

Fax (602) 266-8595

Web www.Interfacett.com<http://www.interfacett.com/>

Email ***@***.******@***.***>

3115 N. 3rd Ave Park Central Mall Suite G-130 Phoenix, AZ 85013

[http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/facebook_sig.png]<https://www.facebook.com/InterfaceTraining>  [http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/twitter_sig.png] <https://twitter.com/interfacett>   [http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/linkedin_sig.png] <https://www.linkedin.com/company/55495>





________________________________

**Comment by R-C-Stewart** [comment]
This lab has been retired.  Apologies for the issues you and students have faced.
