### ISSUE TITLE
Lab 01 - Ex 6 Task 1 - Instructions do not have any relevance

### ISSUE THREAD

**Issue by oilerhead** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#90]
# Module: 01
### Task: 1

Description of issue: The user referenced is not in the CSV and is not created at anytime in the previous lab steps.  As well, the lab asks to assign a Windows license but there are no instructions on how to obtain licenses to assign.  The trial licenses available to active (EMS E5 and AAD P2) are not referenced at anytime in the lab.  There is no option to activate trial Windows licenses.

**Comment by R-C-Stewart** [comment]
This issue was fixed - there is a CSV file provided in the Allfiles/Labs/Lab1 folder for this lab.
