### ISSUE TITLE
Lab 18 - Ex 1 Task 2 Step 5 Error

### ISSUE THREAD

**Issue by rlopezgarcia** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator#99]
# Module: 03
#### Step: 05

When you click + Create policy. Select Access policy.
It shows an error message:

You don't have any apps deployed with Conditional Access App Control. Go to Conditional Access App Control page to deploy an app.

Repro steps:
 Follow the lab instructions
1.
1.
1.

**Comment by rlopezgarcia** [comment]
Doing a little research, there are a few steps missing in the instructions of the lab.
Making reference to the documentation: https://learn.microsoft.com/en-us/defender-cloud-apps/proxy-deployment-aad

You should:
**Before proceeding, make sure to first sign out of existing sessions.

After you've created the policy, sign in to each app configured in that policy. Make sure you sign in using a user configured in the policy.

Defender for Cloud Apps will sync your policy details to its servers for each new app you sign in to. This may take up to one minute.**

I tried it sign in to OneDrive using the MOD Admin account, and now it worked.
Please include this steps on the labs's instrucctions.

**Comment by R-C-Stewart** [comment]
A new version of Lab 18 has been posted.  This issue should be fixed as of Friday September 30.
